name: Xcode - Integration Testing

# Note: This CI/CD function is optimized to pull as much activity as possible out of a single action. It might not be optimized for your use case.

on:
  workflow_dispatch:
  schedule:
    - cron: '*/40 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.release.id || github.ref }}
  cancel-in-progress: true

jobs:
  ui-tests:
    timeout-minutes: 24
    runs-on: macos-latest

    env:
      PROJECT_NAME: "Embrace Ecommerce"

    steps:
    - uses: actions/checkout@v5

    - name: Set up Xcode
      run: |
        sudo xcode-select --print-path

    - name: Set Embrace appId
      run: |
        if [[ -n "${{ vars.APP_ID }}" ]]; then
          sed -i.bak "s/static let appId = \".*\"/static let appId = \"${{ vars.APP_ID }}\"/g" "${{ env.PROJECT_NAME }}/Services/SDKConfiguration.swift"
        else
          echo "APP_ID not found in repository variables"
          exit 1
        fi

    - name: Run UI Tests
      run: |
        xcodebuild test \
          -scheme "${{ env.PROJECT_NAME }}" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
          -only-testing:"${{ env.PROJECT_NAME }}UITests/Embrace_EcommerceUITests/testAuthenticationGuestFlow" \
          -allowProvisioningUpdates \
          -skipMacroValidation
