name: Simple CI

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: macos-latest

    env:
      PROJECT_NAME: "Embrace Ecommerce"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: |
        echo "🔧 Setting up Xcode..."
        sudo xcode-select --print-path
        echo "✅ Using Xcode at: $(xcode-select --print-path)"
        sudo xcodebuild -license accept 2>/dev/null || echo "License already accepted"
    - name: Inject APP_ID
      run: |
        echo "🔧 Injecting APP_ID into code..."
        if [[ -n "${{ vars.APP_ID }}" ]]; then
          echo "✅ APP_ID found: ${{ vars.APP_ID }}"
          sed -i.bak "s/static let appId = \".*\"/static let appId = \"${{ vars.APP_ID }}\"/g" "${{ env.PROJECT_NAME }}/Services/SDKConfiguration.swift"
          echo "✅ APP_ID injected successfully"
        else
          echo "❌ ERROR: APP_ID not found in repository variables"
          exit 1
        fi
    - name: Run UI Tests
      run: |
        echo "🧪 Running UI tests..."
        xcodebuild test \
          -scheme "${{ env.PROJECT_NAME }}" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
          -only-testing:"${{ env.PROJECT_NAME }}UITests/Embrace_EcommerceUITests/testAuthenticationGuestFlow" \
          -allowProvisioningUpdates \
          -skipMacroValidation
        echo "✅ UI tests completed successfully"